### PR TITLE
Settings: Add preference for maximum screen refresh rate

### PR DESCRIPTION
**Pull request by GtrCraft**
* also add icon kanged from OPSettings

Change-Id: I66753b44cc55696783077ebfff3ec6c1dbd268b0

### CODE REVIEW

**Comment by gwolf2u** [comment]
Whats the difference from min refresh settings?
Screenshot_20210421-085704_Settings
Screenshot_20210421-085723_Settings

**Comment by GtrCraft** [comment]
To be able to change max refresh rate as well:
Screenshot_20210421-084716_Instellingen
Screenshot_20210421-084620_Instellingen

**Comment by GtrCraft** [comment]
I don't get the smooth display option because surya has a 120hz screen.
And this should work on oneplus devices as well

**Comment by gwolf2u** [comment]
> 
> 
> I don't get the smooth display option because surya has a 120hz screen.
> And this should work on oneplus devices as well

try
https://github.com/crdroidandroid/android_device_oneplus_sm8150-common/commit/9141f4edb0e0a951effb4a2dcf7fdb6baf1b99da

**Comment by GtrCraft** [comment]
I cant't choose between max 120 and 90hz with that setting.

**Comment by gwolf2u** [comment]
@mukesh22584 
please test this one
according to @firebird11, all is good, yet willing to confirm with more devices

**Comment by mukesh22584** [comment]
> @mukesh22584
> please test this one
> according to @firebird11, all is good, yet willing to confirm with more devices

Sure Sir.

**Comment by gwolf2u** [comment]
solved in https://github.com/crdroidandroid/android_packages_apps_Settings/pull/100

**Pull request closed without merging**
