### PR TITLE
Battery: show battery temp on power summary

### PR DESCRIPTION
**Pull request by Razziell**
Signed-off-by: mdeejay <mdjrussia@gmail.com>
Signed-off-by: DennySPB <dennyspb@gmail.com>
Change-Id: Iff2ed19f59f9b9edcc466840a1ba0d385e29ff07
Signed-off-by: NurKeinNeid <mralexman3000@gmail.com>

### CODE REVIEW

**Comment by Razziell** [comment]
photo_2020-05-15_00-09-47

**Review by gwolf2u — APPROVED** [review]

**Comment by neobuddy89** [comment]
String should be in crdroid settings.

**Comment by Razziell** [comment]
> String should be in crdroid settings.

There are no cr strings in the settings, only cm/lineage - create or add to another place?

**Comment by gwolf2u** [comment]
> > String should be in crdroid settings.
> 
> There are no cr strings in the settings, only cm/lineage - create or add to another place?

add them here
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/10.0/res/values/cr_strings.xml

reason for that is to be able to translate string

**Comment by neobuddy89** [comment]
@gwolf2u this doesn't require divider or any device specific changes? If
yes, need to make it optional. Will test it soon ..

**Comment by gwolf2u** [comment]
tested on poco
worked out of the box
haven't had time to check guacamole

**Comment by neobuddy89** [comment]
--- do not merge ---

**Pull request closed without merging**
