### PR TITLE
Settings: Update RU translations

### PR DESCRIPTION
**Pull request by pixelase**

### CODE REVIEW

**Comment by pixelase** [comment]
@alviteri This one should be ok.

**Comment by alviteri** [comment]
https://github.com/Pixelase/android_packages_apps_Settings/commit/8785f337c08a65db77781375e4934452ab8d0844#diff-5968896986d632014b569a7614e4e954R615

Is not present anymore check

**Comment by alviteri** [comment]
Check this too 
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/28b3ba58fb80c66b06f3a84bf6cedaa67221d8e8

**Comment by pixelase** [comment]
@alviteri I deleted it before, this pull doesn't contain battery strings.
In other words, my commit delete them.

**Pull request merged**
