### PR TITLE
avatar in search bar

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Does it add Avatar to lockscreen as well by default? If yes, this should not be merged.

**Comment by Hikari-no-Tenshi** [comment]
Without this commits on my OnePlus 7 avatar always visible in Settings search bar (and not clickable) though multi user switch is disabled. With this changes avatar will be hidden if multi user switch is disabled and will be clickable when multi user switch is enabled.
On lockscreen avatar will appear only if multi user switch is enabled. And this behavior does not depend on those commits, same thing without commits.

**Comment by neobuddy89** [comment]
Why not only add second commit?

**Comment by Hikari-no-Tenshi** [comment]
Second commit depends on changes from first commit.
Not sure if i can correctly apply changes only from second commit..

**Comment by Hikari-no-Tenshi** [comment]
Tested changes to only show/hide icon and must say that we need both commits.
Without first commit visible icon is useless (when you tap it nothing happens).

**Comment by gwolf2u** [comment]
I'd say we can add those
It will remove icon as long as multiuser case is not set

**Comment by gwolf2u** [comment]
We can also set multiuser switch to off by default
Or is it off already?

**Comment by Hikari-no-Tenshi** [comment]
Looks like it's on by default https://github.com/crdroidandroid/android_frameworks_base/commit/c69c8b60084b13fe5e4d6d299708b5ca248ecc36

**Comment by neobuddy89** [comment]
What's multiuser switch?
Multiuser ability (adding new users) is present and required on all devices.
However, by design, only if there are more than 1 user added, it should show avatar on lockscreen.
With this commit, I think, it will enable by default even if there is only 1 user for device. Many users objected this behavior in past.

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> What's multiuser switch?
> Multiuser ability (adding new users) is present and required on all devices.
> However, by design, only if there are more than 1 user added, it should show avatar on lockscreen.
> With this commit, I think, it will enable by default even if there is only 1 user for device. Many users objected this behavior in past.

Multi user switch is in Settings --> System --> Multiple users

When this switch enabled Multi user icon shown on lockscreen and on Settings search bar. And this icons do nothing when you tap them, they just indicate that multi user is enabled.

By default icon on Settings search visible always. Those two commits fixing this issue and adding ability to open Multiple user settings by tapping icon.

**Comment by neobuddy89** [comment]
What about lockscreen? Default behavior shows no avatar. Will this commit add avatar to lockscreen?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> What about lockscreen? Default behavior shows no avatar. Will this commit add avatar to lockscreen?

Don't think it will affect lockscreen.

When i flashed crDroid for the first time few months ago there where no icon on lockscreen, but after some update in the beginning of April this icon appeared on lockscreen by itself. To hide icon on lockscreen i disabled Multi user switch. On lockscreen icon disappeared, but on Settings search bar remained visible.

**Comment by neobuddy89** [comment]
Added with cleanup below:
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/5b43187ebf5efc3e3993a6e357cca74bad6e980a

**Pull request closed without merging**
