### PR TITLE
Revert "Update the battery saver scheduler minimum level"

### PR DESCRIPTION
**Pull request by gstjee**
- that commit was creating issue: value set lower than default(20) was not persisting after reboot. 
- as currently  minimum possible value is 10% so given that we don't need to change code as well so simply reverting that commit is suffice.
This reverts commit b0fe225a17f91cdac8a82a2ff0f25ca19b5bf1bb.

### CODE REVIEW

**Comment by neobuddy89** [comment]
shouldnt this sync with level mentioned in battery drawables in fw base?

**Comment by gstjee** [comment]
> shouldnt this sync with level mentioned in battery drawables in fw base?

are you referring to this:  **"config_lowBatteryWarningLevel">20<**  in FB?
if is it so then after reverting  that commit it effectively set default value(10) which is i intended. But then again we got to know another issue "why FB is not overlaying it's value(20)"
 
 **to sum up:**
 1.  why FB' config_lowBatteryWarningLevel is not effective ?
 2.  for the issue arose from that commit: ig either we need to update code logic to handle values set by users lower then default(20) or simply  revert that commit to avoid any code changes.

**Comment by neobuddy89** [comment]
I am not able to reproduce issue you mentioned.
Battery saver does persist at 10% after boot.

**Comment by Terminator-J** [comment]
> I am not able to reproduce issue you mentioned. Battery saver does persist at 10% after boot.

At that point, pull down the shade, and toggle Battery Saver QS Tile on & back off, then go back into Battery Saver > Schedule setting, and you'll see that it has reset back up to 20%.

I've been able to reproduce the issue on enchilada & fajita, and including the revert seems to fix it.

**Comment by gwolf2u** [comment]
Ignore secure flag will never be added

**Comment by gstjee** [comment]
> Ignore secure flag will never be added

seems like force push in forked repo leads to open pull for another commit as well.   
ignore that.

**Comment by gstjee** [comment]
this is still unresolved as we still requires revert commit to rectify issue. 
But now closing this pull because force push in local repo causing issues like unnecessary  workflows creation and leading to new pulls as well.

**Comment by Terminator-J** [comment]
Make a new branch in your forked repo that tracks current crDroid 14.0 branch with just the revert commit on top, and open pull request from that.

**Comment by gstjee** [comment]
@Terminator-J thanks for suggestion. raised it again https://github.com/crdroidandroid/android_packages_apps_Settings/pull/150

**Pull request closed without merging**
