### PR TITLE
Updata Chinese translation.

### PR DESCRIPTION
**Pull request by TigerBeanst**
Updata Chinese translation.

### CODE REVIEW

**Comment by alviteri** [comment]
did you compiled with it?
it is buildable?

**Comment by TigerBeanst** [comment]
No, but it is just a xml for updating Chinese translation.

**Comment by alviteri** [comment]
build it first and then I will merge this otherside I will let it opened

**Comment by TigerBeanst** [comment]
Sorry...I do not how to build it. I just translate it.

**Pull request merged**
