### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gwolf2u** [comment]
what is this exactly?

**Comment by ghost** [comment]
if it's useful please add it, otherwise. No problem.

**Comment by neobuddy89** [comment]
This activity is already defined. Why adding again? Also, please avoid sending pull request without proper justification and commit message.

**Comment by ghost** [comment]
Okay sir, i'm sorry.

Kamis, 08 Februari 2018, Pranav Vashi <notifications@github.com> menulis:

**Pull request closed without merging**
