### PR TITLE
BatteryHealth: Charge cycles & Battery Capacity

### PR DESCRIPTION
**Pull request by ghost**
Read Charge Cycles, Battery Designed Capacity & Battery Current Capacity from Battery settings. Not every device have the charge full & charge full design files at the same location or same name.
Better to keep it overlayable for maintainer to pick.
Overlay would be for Settings - overlay/packages/apps/Settings/res/values/x_config.xml
Overlay Ex -:

    <string name="config_batDesCap">/sys/class/power_supply/bms/charge_full_design</string>
    <string name="config_batCurCap">/sys/class/power_supply/bms/charge_full</string>
    <string name="config_batChargeCycle">/sys/class/power_supply/bms/cycle_count</string>
    <bool name="config_supportBatteryHealth">true</bool>
    

Commid-Id: 37b74aed3f56381250fa2e7dbd28a4947e8c18e1 &
Commid-Id: 23bcbd34a21fc3a00014c9397e78207fd5a0d434

Signed-off-by: Prince Cooper <pcooper7736@gmail.com>
Co-Authored-By: SuperDroidBond <superdroidbond@yahoo.com>

Screenshot_20210829-193322873~01

### CODE REVIEW

**Comment by neobuddy89** [comment]
it should be available only if readable/available on device.

**Comment by ghost** [comment]
> it should be available only if readable/available on device.

Yes, made it overlayable btw. Battery Health Stats [will be false bydefault.](https://github.com/crdroidandroid/android_packages_apps_Settings/blob/d624410338c00ef0756758ea1a16be643921b7de/res/values/config.xml#L473) 🙂

**Comment by neobuddy89** [comment]
You have added 
bool name="config_supportBatteryHealth">false</bool
in xml

but nowhere used in code.

**Comment by ghost** [comment]
> You have added
> bool name="config_supportBatteryHealth">false</bool
> in xml
> 
> but nowhere used in code.

Ah, yes, will edit the pr. Also I've had unused variable FILENAME_BATTERY_DESIGN_CAPACITY, will cleanup lil bit & repull it.

**Comment by xNombre** [comment]
Please dont use abbreviated names, these appear harder to understand and its completely ok to use long names. My proposition:
config_batDesCap -> config_batteryDesignCapacity
config_batCurCap -> config_batteryCalculatedCapacity
config_batChargeCycle -> config_batteryChargeCycles

**Comment by neobuddy89** [comment]
Added.

**Pull request closed without merging**
