### PR TITLE
Bring back SeLinux version

### PR DESCRIPTION
**Pull request by gwolf2u**
This includes the work previously done by Fan Zhang <zhfan@google.com> since it was introduced in 2012.

Change-Id: Ic371a9ef0055b559eb0b6ff2791291fb82e408cf

### CODE REVIEW

**Comment by neobuddy89** [comment]
Available under security > trust.

**Comment by gwolf2u** [comment]
I know yet trust it not that widely used 
think we should consider this old way of viewing

**Comment by neobuddy89** [comment]
About is already crowded with different set of infos. These doesn't add any value either. Most users would know or won't care selinux status.

**Comment by gwolf2u** [comment]
OK for me then

**Pull request closed without merging**
