### PR TITLE
Settings: Update RU translations

### PR DESCRIPTION
**Pull request by pixelase**

### CODE REVIEW

**Comment by pixelase** [comment]
@alviteri Hi. Why you close this pull?

**Comment by alviteri** [comment]
Hi I don't close this I will merge it soon

**Comment by alviteri** [comment]
Just check dialer lock screen icon isn't present anymore

**Comment by pixelase** [comment]
@alviteri Ok, no problem)

**Comment by alviteri** [comment]
@Pixelase Please resolve the conflicts and I will merge this check what strings are not needed anymore 

Thanks for your help with translations

**Comment by pixelase** [comment]
@alviteri I delete the unused strings(battery strings), but it is still contains merge conflicts. I don't know? what is it. This has happened before. I use the web version of github and I can't rebase all commits into one. So i just now will close this pull, fork again this repo and try to open new with ony one commit. It should be okay.

**Comment by alviteri** [comment]
Ok

**Pull request closed without merging**
